### PR TITLE
added fancy nocked test (fix #1)

### LINKED ISSUE #1: add tests
Test using the actual api. Possible with encrypted credentials (like [here](https://github.com/ismay/ismay.github.io/blob/development/.travis.yml#L18)). See:
- http://stackoverflow.com/questions/9338428/using-secret-api-keys-on-travis-ci
- https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests

### PR DESCRIPTION
**Pull request by leviwheatcroft**
lots of dev dependencies :-/

### CODE REVIEW

**Comment by ismay** [comment]
Nice! That's great 😃  I'll take a look at it during the weekend, thanks for the PR!

**Comment by leviwheatcroft** [comment]
These 2 commits fix #2 re: caching requests to cloudinary.

IDK if it's poor form to make ES6 changes to someone elses repo? If you're not a fan just let me know.

**Comment by ismay** [comment]
> IDK if it's poor form to make ES6 changes to someone elses repo? If you're not a fan just let me know.

I don't think so, in fact I think it's great 👍 . Took a look at the pr, everything looks good, only thing I wanted to ask is if you could remove dist/ and add it to .gitignore.

One thing I haven't seen before is [the `node4` folder in dist](https://github.com/superwolff/metalsmith-cloudinary/pull/4/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R11), will that be picked up automatically by node 4?

**Comment by leviwheatcroft** [comment]
The dist folder contains the transpiled node6 code. I forgot to change package.json `main` property to `dist/index.js`, but that's what it should be. 
I'll remove node4 compatibility, it's only there because I copied the package.json from another repo. Just out of interest though you'd consume the node4 version with `require('metalsmith-cloudinary/node4')`, so it's not automatic, but convenient.

**Comment by ismay** [comment]
> The dist folder contains the transpiled node6 code. I forgot to change package.json main property to dist/index.js, but that's what it should be.

I see, but you don't need `/dist` in the repo though. Just as a prepublish hook is good enough. I personally find committing it just clutters up the diffs.

Btw., usually I try to support the same node version with my plugins as metalsmith/metalsmith, but I'll leave the decision to you.

**Comment by leviwheatcroft** [comment]
Yeah right, I always thought that npm just linked to a commit tag, but [reading about it now](https://docs.npmjs.com/misc/developers) I realise that it's more like a snapshot of your current file system, which excludes a bunch of things. TIL.

So it sounds like I need to copy `.gitignore` to `.npmignore` then add `dist` to `.gitignore`.. I'll check but I think there's already a prepublish hook, or maybe a verison hook.

**Comment by ismay** [comment]
> So it sounds like I need to copy .gitignore to .npmignore then add dist to .gitignore.

At a glance, yeah I would say so. Basically ignore everything but the source in gitignore, and ignore everything but the build result in your npmignore. This is what works well for in-place for example:

* [.npmignore](https://github.com/superwolff/metalsmith-in-place/blob/master/.npmignore)
* [.gitignore](https://github.com/superwolff/metalsmith-in-place/blob/master/.gitignore)

> I'll check but I think there's already a prepublish hook, or maybe a verison hook.

Yeah, the [version](https://github.com/leviwheatcroft/metalsmith-cloudinary/blob/e84406dd92753c0c4bf1f320edd9074036340c63/package.json#L15) hook does the same I believe.

**Comment by leviwheatcroft** [comment]
think this is good to go now.

**Comment by ismay** [comment]
Cool, thanks again for the pr!

**Comment by ismay** [comment]
Published as 0.2.0

**Pull request merged**
